#!/bin/bash

#ECDSA
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/CN=192.168.1.75"

#RSA
#openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=RU/ST=Moscow/L=HP/O=ESP32/CN=192.168.1.75"
